### ISSUE TITLE
Delete (?) Usage section from README until we can update it

### ISSUE THREAD

**Issue by mbonsma** [phageParser/phageParser#180]
The [Usage](https://github.com/phageParser/phageParser/blob/master/README.md#usage) section of the README is super out of date and doesn't work as written anymore. I think we can delete it entirely until we can update it, but if anyone knows which parts specifically aren't working we can leave in the rest.

**Comment by wgma00** [comment]
So in the [Makefile](https://github.com/phageParser/phageParser/blob/master/Makefile#L71), the rule for `filter_by_expect` invokes ``filterByExpect.py`` as an executable. But this returns an error since the file normally only has read/write permissions. And when you do give it execution permissions, then use the following example  ``make filter_by_expect infile=data/blast-phagesdb.txt output=output/ threshold=0.21``  it crashes because the source file treats the infile as a [directory](https://github.com/phageParser/phageParser/blob/master/filterByExpect.py#L64)

**Comment by thegreyelephant** [comment]
I'll work on this one!
